# Generated by Django 5.2 on 2025-04-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_userskill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
