# Generated by Django 5.2 on 2025-04-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_skill_is_featured'),
        ('users', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='user_skills', to='users.qualification'),
        ),
    ]
