# Generated by Django 5.2 on 2025-04-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='qualification_image',
            field=models.ImageField(blank=True, null=True, upload_to='qualifications/'),
        ),
    ]
