# Generated by Django 5.2 on 2025-04-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_qualification_qualification_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_image',
        ),
    ]
