# Generated by Django 5.1.7 on 2025-05-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_qualification_qualification_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
