# Generated by Django 5.1.7 on 2025-04-01 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('proposed_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_offered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_in_swaps', to='skills.skill')),
                ('skill_requested', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_in_swaps', to='skills.skill')),
            ],
            options={
                'db_table': 'skill_swap_requests',
            },
        ),
    ]
