# Generated by Django 5.2 on 2025-04-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaps', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillswaprequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
